version: 0.0
os: linux
files:
  - source: /Dockerfile
    destination: .
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/run_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
