version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: "scripts/run_nginx"
      timeout: 300
      runas: root
  ApplicationStop:
    - location: "scripts/stop_nginx"
      timeout: 300
      runas: root
